### ISSUE TITLE
IHaveIdentity required by read model classes

### ISSUE THREAD

**Issue by galenp** [liquidprojections/LiquidProjections.RavenDB#2]
I'd like to keep my Component.Query project used for my API seperate from my Component.Projections project by having a shared Component.ReadModel assembly.

The Component.Projections would include the references to LP, NEventStore polling client etc.

My API would have no dependencies on these libraries and just query the RavenDB directly for the read model.

However the LP RavenProjector requires that the read model implement IHaveIdentity.

I thought perhaps have a container class in the Component.Projections project that wraps the read model and implements IHaveIdentity... but I assume this will cause Raven to serialize this type and cause problems when querying.

What is ths suggested way around this?

**Comment by dennisdoomen** [comment]
Yeah, I see your point. I think I should drop that interface and have the consumer provide a lambda that the projector can use to determine the identity instead. Would that make sense?

**Comment by galenp** [comment]
Had any further thoughts on this Dennis? I should of replied in here instead of Twitter msg. I did have a look myself to maybe do a PR , but I got a bit lost in it all tbh.

**Comment by dennisdoomen** [comment]
Yes, I was planning to do that last week, but upgrading the existing packages to LiquidProjections 2.0 proved a bit more work.
